name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*'   # triggers on tags like v1.0.0, v2.3.4, etc.

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # allows publishing to GitHub Packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
